### ISSUE TITLE
Add validation for parser setters

### ISSUE THREAD

**Issue by prydonius** [prydonius/spinning_cursor#15]
This will be a bit more involved since the getters and setters are implemented via metaprogramming.

The validations should be:
- `type` - must be a method in `SpinningCursor::Cursors`
- `delay` - must be a real number (`to_i` if it isn't?)
- `output` - must either be `:inline` or `:at_stop`
- `banner` and `message` - must be strings (`to_s` if it isn't?)

Either we can implement more metaprogramming e.g. "validation_#{option}" methods, or separate each getter and setter into their own methods.

I prefer the latter, I feel it will be less messy, and there are only 5 options at the moment, not 100s so `define_method` isn't really needed! It was just a quick hack at the time.

Also, an error should be thrown if validation fails.

**Comment by abinoam** [comment]
I'm using to_f (not to_i) for delay.
Kept your metaprogramming scheme. 
I think it didn't got too messy.
(We can rewrite later, if you prefer).
