### ISSUE TITLE
Non-deterministic test for changing banner whilst running

### ISSUE THREAD

**Issue by prydonius** [prydonius/spinning_cursor#17]
Every now and then this test fails, most likely this is a timing issue.

"whilst running it should allow you to change the banner. (TestSpinningCursor)"

**Comment by prydonius** [comment]
I'm running the tests in a loop and have discovered another non-deterministic test:

```
Error:
test: API should raise CursorNotRunning errors when cursor has run and finished.
 (TestSpinningCursor):
SpinningCursor::CursorNotRunning: Can't stop, no cursor running.
    /scratch/aa/ruby/spinning_cursor/lib/spinning_cursor.rb:79:in `rescue in sto
p'
    /scratch/aa/ruby/spinning_cursor/lib/spinning_cursor.rb:55:in `stop'
    /scratch/aa/ruby/spinning_cursor/test/test_exceptions.rb:22:in `block (2 lev
els) in <class:TestSpinningCursor>'
    /home/local/aa/.gem/ruby/1.9.1/gems/shoulda-context-1.1.4/lib/shoulda/contex
t/context.rb:400:in `call'
    /home/local/aa/.gem/ruby/1.9.1/gems/shoulda-context-1.1.4/lib/shoulda/contex
t/context.rb:400:in `block in create_test_from_should_hash'
```

**Comment by abinoam** [comment]
I have managed to reproduce the first one.

  1) Failure:
test: whilst running it should allow you to change the banner. (TestSpinningCursor) [/Users/abinoam/src/spinning_cursor/test/test_spinning_cursor.rb:118]:
It should have changed banner.
<true> expected but was
<false>.

**Comment by abinoam** [comment]
My "bird's eye" guess... race conditions.

**Comment by abinoam** [comment]
Managed to reproduce the other one...

  1) Error:
test: API should raise CursorNotRunning errors when cursor has run and finished. (TestSpinningCursor):
SpinningCursor::CursorNotRunning: Can't stop, no cursor running.
    /Users/abinoam/src/spinning_cursor/lib/spinning_cursor.rb:79:in `rescue in stop'
    /Users/abinoam/src/spinning_cursor/lib/spinning_cursor.rb:55:in`stop'
    /Users/abinoam/src/spinning_cursor/test/test_exceptions.rb:22:in `block (2 levels) in <class:TestSpinningCursor>'
    /Users/abinoam/.rvm/gems/ruby-1.9.3-p429@spinner/gems/shoulda-context-1.1.4/lib/shoulda/context/context.rb:400:in`call'
    /Users/abinoam/.rvm/gems/ruby-1.9.3-p429@spinner/gems/shoulda-context-1.1.4/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'

**Comment by abinoam** [comment]
Think I've solved the first.
Testing now.
