### ISSUE TITLE
Different timing values upon second run

### ISSUE THREAD

**Issue by abinoam** [prydonius/spinning_cursor#4]
When running something like bellow two times on the same script it renders erroneous finished time values.

``` Ruby
SpinningCursor.start
sleep 1.5
result = SpinningCursor.stop
timing_1 = result[:finished] - result[:started]
```

This is probably caused by the Spinning Cursor relying on the fact that instance variables are set to nil upon initialization. But, at the second run, they retain the last value causing the bug.

I'm working on it. Pull request soon.

**Comment by prydonius** [comment]
Good spot, thanks!
